version: '2'
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd src/src/rest && ls && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      - ${ADBREW_CODEBASE_PATH}/tmp:/tmp
      - ${ADBREW_CODEBASE_PATH}:/src

  app:
    build: .
    container_name: app
    command: bash -c "cd src/src/app && yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/src

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/db/:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    platform: linux/arm64/v8

  test:
    build: .
    container_name: app_test
    command: bash -c "cd src/src/app && yarn install && yarn test"
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/src
